### PR TITLE
Byshape fixes

### PR DESCRIPTION
**Pull request by JATothrim**
I hope refactoring out CubeView does not conflict with your plans with it. :)
I refactored the interfaces so that CacheReader users don't go poking the implementation.

### CODE REVIEW

**Comment by nsch0e** [comment]
Yeah, my plan with it was, that we could use it as an overlay over existing data and never have to actually copy the data. Further plans for Cube representation were to compress them, which results in different sized entries. This was the reason I started CubeView.

In the end I landed at a class almost looking like Cube and also had to copy everything into a Cube for further processing. So having a custom Iterator for Cubes makes absolutely sense.

> Mixing C APIs with C++

In my PR you said we should not mix the APIs. I would agree, but I'm not aware of a C++ style memory-mapped file. Or would you rather use std::ifstream or something and then mmap its filePointer?
Or were you referring to std::printf vs std::cout style?

> The newCache.hpp structs/classes interfaces are laid-out such that I can't read what is the interface for code that uses them and what belongs to the implementation of the structs/classes.

Is this a problem of having all the Iterator classes in it?
Or of having members public, which are just internal state? Should the Iterators have its implementation separated from the declaration? I would imagine that they can be optimized quite well when inlined vs a separate translation unit?

**Comment by JATothrim** [comment]
> In my PR you said we should not mix the APIs. I would agree, but I'm not aware of a C++ style memory-mapped file. Or would you rather use std::ifstream or something and then mmap its filePointer?
Or were you referring to std::printf vs std::cout style?

I was referring mostly to memcpy, printf vs. std::cout etc. 
I don't really like the C++ std::cout for console printing since C++17 doesn't yet have `std::format()` util that fixes this ancient problem in C++. Also rest of the project is already using std::printf().

The file memory mapping is from Unix system API <unistd.h> etc. and these are fine.
std::fopen() would give FILE* that can be passed into C library `fileno()` that gives the OS file handle for `mmap()`
`::open(), mmap()` are OS APIs, `fopen()` is from C library and then there is `std::fopen()` :)
So the using ::open() --> mmap() is good for now.
Just have to be careful not to leak the unix/OS headers out from the CacheReader (the .cpp file)

Unfortunately I don't have the source with me now, but I do have memory mapped file class that works both on linux and windows. And it can actually *write* the mapping back to the file and not just reading it. Maybe next week.

> Is this a problem of having all the Iterator classes in it?

CubeIterator being in newCache.hpp is okay.
> Or of having members public, which are just internal state? 

Definitely an problem. In short, Interface of class is what you can *access* or *call* from object of the class. If you make change to interface (e.g renaming member) any code using that is also now broken.
My mantra of breakage goes: *adding stuff is easy, modifying internals is ok, swapping implementation may work, renaming interfaces is labor camp and removing used interface is nearly impossible.* :laughing: 

> Should the Iterators have its implementation separated from the declaration? I would imagine that they can be optimized quite well when inlined vs a separate translation unit?

Iterator code should stay in an header, but it's data member(s) should be protected/private. There is also sneaky `friend class Workset` that should be removed.

Sorry for wall of text, it's just lot's small details. :smiley:

**Comment by JATothrim** [comment]
@nsch0e I added changes that enable special constructor for Cube:
Cube can now directly access any memory it doesn't own - so it can act like the CubeView.

About the compression plans for cubes, if I understand correctly:
We want to compress the XYZ data on *disk*, this means we are have to decompress into RAM at some point for the data to be usable. Decompressing just few bytes at time (for single Cube) would be inefficient.
I think best place to put the de/compression machinery would at ShapeRange level:

So maybe IShapeRange with virtual begin(), end() functions , ShapeRange derived from that for direct file reading like now and CompressedShapeRange for reading compressed cache file data?
CompressedShapeRange ctor would take "filePointer memory range" and some info needed to decompress + interpret this data. It would then decompress the data and begin() would just return CubeIterator pointing into the decompressed Cubes. (the decompressed data is kept in CompressedShapeRange)

That way getCubesByShape() could return either (as `std::unique_ptr<IShapeRange>`)  ShapeRange or CompressedShapeRange
And the ICache interface users would none the wiser where the data came from :)

For writing the data back to disk, I'm not yet too familiar with the file format and what the requirements are.

**Comment by nsch0e** [comment]
> There is also sneaky `friend class Workset` that should be removed.

I know all the tricks. ;)

> Unfortunately I don't have the source with me now, but I do have memory mapped file class that works both on linux and windows. And it can actually _write_ the mapping back to the file and not just reading it. Maybe next week.

Sounds handy. The write part is interesting and I'm wondering how its done, when we don't know the actual resulting size before mapping.

> We want to compress the XYZ data on _disk_, this means we are have to decompress into RAM at some point for the data to be usable. Decompressing just few bytes at time (for single Cube) would be inefficient.

Not exactly. I have a compression for a single Cube which is ~5x smaller than a normal Cube.
I don't think that compression only applies to cache files. Our RAM usage is the most constraining factor. So if we can reduce size in RAM we should do it.
This would also mean that we store Cubes in the compressed state in the hashtable. I would say that compression/decompression overhead is negligible compared to swapping. 

> So maybe IShapeRange with virtual begin(), end() functions , ShapeRange derived from that for direct file reading like now and CompressedShapeRange for reading compressed cache file data?

Yes, but if this doesn't violate c++ "laws" I would like to only decompress Cubes one-by-one when they are returned by the iterator. We are talking multiple GBs/shape allocating and decompressing vs only one Cube.

> For writing the data back to disk, I'm not yet too familiar with the file format and what the requirements are.

File format is very simple at the moment:
FileHeader | ShapeTable | XYZs
FileHeader has basic information (N, #shapes, #totalCubes)
ShapeTable contains information about each shape and its offset/size into XYZ block

New file format would be the same but with variable size of each Cube (not n*XYZ).
CompressedCube:
len (uint8_t) | encoded-data (len * uint8_t)

iterator over CompressedCubes has to jump variable size in cache file depending on encoding len.



> I added changes that enable special constructor for Cube:
> Cube can now directly access any memory it doesn't own - so it can act like the CubeView.

Did you push them to this PR? or where do I find them?

**Comment by nsch0e** [comment]
unfortunately this broke using cache -.- the recursive version works fine, but using cache above n=5 gets wrong results

**Comment by JATothrim** [comment]
> unfortunately this broke using cache -.- the recursive version works fine, but using cache above n=5 gets wrong results

Welp that's a problem, I'll look into it what went wrong...
Edit: I bisected it to https://github.com/nsch0e/opencubes/pull/13/commits/35488805d1e4e6ac2427d55d70b348becee162b4

**Comment by nsch0e** [comment]
Problem seems to be `ShapeRange CacheReader::getCubesByShape(uint32_t i)` when it constructs ShapeRange with wrong "size".

Root problem is the ambiguous membername "size" because it is the cubeLen aka N.

Edit: @JATothrim would you review my changes in #15 so we again get a working byshape branch :)

**Pull request merged**
