### PR TITLE
Reformatting For Readability.

### PR DESCRIPTION
**Pull request by bertie2**
Reformatting a little for readability, main changes:

- split code from struct definitions where large functions where present.
- made cmake config a little more generic.
- improved the .gitignore to remove some of the chaff generated by cmake
- added a DEBUG_PRINTF #define to pretty up the printing in some places.

- broke main into its own file and added a simple command line parsing library.
  I was a little torn on this as to whether this should be included.

  1. it makes us MIT license that part of the project.

  2.  I wasn't sure whether to add it as a submodule or a raw file, I eventually opted to include it directly but could be convinced to submodule it.
    
    this is definitely the change I'm least happy with so feel free to ask for revert.

hope this helps and let me know your thoughts.

### CODE REVIEW

**Comment by bertie2** [comment]
final note, in reality I would also like to refactor the big functions out of hashes.hpp into a hashes.cpp but since its templated you can't, is their a specific reason Hashy is templated ? we never seem hash anything else with it but cubes.

**Comment by bertie2** [comment]
also added the framework for unit tests (and a couple of example tests) though this can be backed out if needed.

**Comment by JATothrim** [comment]
I build tested and following doesn't compile on GCC:
-`checkout nsch0e/cpp`
-`pull bertie2 reformating`

Issues that I found:
-There is no `<stdint.h>` (this is C library header) in C++, please replace with `<cstdint>`
-Non existent `uint` type, just use `int`?
-`#include <array>` maybe missing  in `hashes.hpp`?

Fixing these I got it to build on gcc. I like the separation of the implementation to .cpp files.

**Comment by bertie2** [comment]
> I build tested and following doesn't compile on GCC: -`checkout nsch0e/cpp` -`pull bertie2 reformating`
> 
> Issues that I found: -There is no `<stdint.h>` (this is C library header) in C++, please replace with `<cstdint>` -Non existent `uint` type, just use `int`? -`#include <array>` maybe missing in `hashes.hpp`?
> 
> Fixing these I got it to build on gcc. I like the separation of the implementation to .cpp files.

should be fixed now, apologies my build env is a bit loosy goosy as its used for many projects, might be worth dockerizing the build eventualy.

**Comment by JATothrim** [comment]
I pulled again and now it looks okay.
- Builds OK with GCC
- Main program runs Ok.
- The test suite added also builds, runs and passes.

However I think there are few bits that could be improved:

- tests/README.md confused me as it tells to `git submodule --init --recursive` but this is wrong, because tests/CMakeLists.txt actually uses FetchContent to pull in the library during configure.
- tests is built as separate CMake project, so now I have to configure *two* build directories.
- `HashCube` and `CubeSet` was moved to `hashes.hpp`, but `XYZHash` was not.
I think these should remain in `cube.hpp` and keep hashes.hpp for Hashy code.


@bertie2: Would it be okay for me to refactor the CMakeLists.txt(s) to better integrate the build?

**Comment by bertie2** [comment]
> I pulled again and now it looks okay.
> 
> * Builds OK with GCC
> * Main program runs Ok.
> * The test suite added also builds, runs and passes.
> 
> However I think there are few bits that could be improved:
> 
> * tests/README.md confused me as it tells to `git submodule --init --recursive` but this is wrong, because tests/CMakeLists.txt actually uses FetchContent to pull in the library during configure.
> * tests is built as separate CMake project, so now I have to configure _two_ build directories.
> * `HashCube` and `CubeSet` was moved to `hashes.hpp`, but `XYZHash` was not.
>   I think these should remain in `cube.hpp` and keep hashes.hpp for Hashy code.
> 
> @bertie2: Would it be okay for me to refactor the CMakeLists.txt(s) to better integrate the build?

sure thing, if you raise a pull request on my repo il accept, otherwise, il make the changes myself shortly.

**Comment by nsch0e** [comment]
When you are ready, then I would pull your changes. So all further work is on the clean state.

**Comment by nsch0e** [comment]
I'm getting compile warnings with g++ 9.4.0
```
opencubes/cpp/libraries/cmdparser.hpp:331: warning: ignoring #pragma warning  [-Wunknown-pragmas]
  331 |     #pragma warning(push)
      | 
opencubes/cpp/libraries/cmdparser.hpp:332: warning: ignoring #pragma warning  [-Wunknown-pragmas]
  332 |     #pragma warning(disable: 4702)
      | 
opencubes/cpp/libraries/cmdparser.hpp:335: warning: ignoring #pragma warning  [-Wunknown-pragmas]
  335 |     #pragma warning(pop)
      | 
```
perhaps we should add `-Wno-unknown-pragmas` to suppress those.

**Comment by bertie2** [comment]
I have suppressed the warnings for the program but not for the tests, since the tests don't test against the external library.
I have also implemented @JATothrim 's changes except for moving HashCube and CubeSet as they are only ever used in the hashes header.
I will leave it to you @nsch0e to decide if you want to move them, otherwise this is ready to merge from my perspective.

**Comment by JATothrim** [comment]
I apparently missed the merge: https://github.com/bertie2/opencubes/pull/4 oops.
I rebase and review my changes and open new pull request shortly.

**Pull request merged**
