### PR TITLE
evenly distribute subhashes to increase speed

### PR DESCRIPTION
**Pull request by bertie2**
rebased my work onto latest code still runs faster, looking now at reworking to still possibly sort by shape
also includes a bugfix where load() assigned a empty Hashy onto hashes when caching was enabled but the file was not found, leading to undefined behavior

### CODE REVIEW

**Comment by nsch0e** [comment]
I am again sry to have corrupted your PR. I think I broke compatibility with cache files. And another interesting fact is, that big file sizes are not read correctly by the load function. So for me cache_13.bin always fails.

Isn't an empty return on read-fail the expected behavior? This should lead to a calculation instead of using the cache...

**Review by JATothrim — COMMENTED** [review]
The templating+forward is needed only for arguments that may be "Cube" or "Cube&&"
Does it compile with "hash_cube(const Cube&)" non-template?

**Comment by nsch0e** [comment]
> bugfix where load() assigned a empty Hashy onto hashes when caching was enabled but the file was not found, leading to undefined behavior

Now I experienced the same issue. Rather than initialize in cache.hpp, I initialize for n=1 and n=2 at their respective special cases in cubes.cpp.

perhaps we should create some simple bigbang tests to ensure we dont break it :D

**Comment by nsch0e** [comment]
i now put 8 subsets behind each shape which gives a small boost in speed. N=13 takes about 180s on an Intel 12700H with 20 Threads.

**Pull request closed without merging**
