### PR TITLE
Implementation cleanup and bug fixes

### PR DESCRIPTION
**Pull request by jiriklepl**
Hi,

I've identified data races in Hashy methods and added shared_mutex to fix them.

Also, I've redesigned the XYZ structure to no longer rely on nonstandard aliasing behavior. The caveat is that my implementation requires c++20 (although that is only because I use default comparison operators, I believe).

I have also slightly improved the build script.

I haven't focused on correcting the engineering and coding style, for that, see #3 - I think it does a very decent job at that.

I hope some of the changes help! And feel free to copy any of the additions if you don't like the redesign.

### CODE REVIEW

**Comment by JATothrim** [comment]
I finished doing the proper patch-set: Go see: https://github.com/nsch0e/opencubes/pull/5

**Comment by nsch0e** [comment]
so style aside, for the Hashy data races: whats the problem with std::mutex? Do you see more problems with the subhashy branch (base for #5) there are multiple sets with mutexes which should get preallocated in a map. I don't know how to force the map to not reallocate after initialization b/c that probably will have bad effects while multithreading.

Your XYZ rework seems really convoluted. I think there are two factors for this class:
1. it has to be fast, b/c its used extremely often -> did you test your changes for performance?
2. should be easy to use (i don't like .x(), but perhaps there is no way around it) -> you changed type to uin8_t but there can be negative numbers... seems unintuitive to check for 255 instead of p.x < 0

I hope we find a less complicated style for this class with proper behaviour. 

You inlined the load and save, but since everything gets compiled in one object file is it needed? When the compiler sees fit it should inline it anyway?

Happy to learn more about C++ and compilers :)

**Comment by jiriklepl** [comment]
The bug was in that .size() method didn't lock the mutex and so it could read incorrect data from the map. Nothing major, but it got picked up by helgrind. There is nothing bad with std::mutex; but std::shared_mutex allows you to nonexclusively lock it so multiple threads can read the size at the same time.

1. Yes, I have and, on my machine, the changes in performance are almost negligible (the implementation is slightly faster, but that is likely due to the other minor changes).
2. I changed it to uint8 just because bit operations on signed integers are easier to get wrong. And the `== 255` is just a check for underflow, it is not that much unintuitive, I think. Underflow on unsigned integers is well-defined behavior in the language standard - not like reading inactive union members.

(The rework more so an exercise in whether the XYZ structure could be implemented to be more standard-friendly while preserving most of the API - a complete redesign could be perhaps simpler)

I added inline to the two methods just because it is bad practice to not to. C++ keyword `inline` does not actually mean you request the function to be inlined. It means that if multiple different .cpp files include the header, the linker should understand that all the `load` and `store` functions are the same - otherwise, the compilation fails due to it assuming you defined multiple different symbols "load" and "store".

**Comment by jiriklepl** [comment]
Reallocation shouldn't be a problem as long as all accesses to the shared structures are under an appropriate lock - has to be unique if your access changes the state, otherwise, can be shared.

I currently cannot analyze the subhashy branch more closely, but if the big map is accessed from multiple threads, there might be some problems. I don't see any obvious bugs.

**Comment by jiriklepl** [comment]
`res` definition on line 69 of cubes.hpp might be changed to [structured binding](https://en.cppreference.com/w/cpp/language/structured_binding) to increase readability, but I don't think it matters much.

**Comment by nsch0e** [comment]
I would like to close this PR. I implemented XYZ without the union but with less abstraction than your solution. You're welcome to look into it and tell me if there is still undefined behavior.

I understand your intention of inline, but since load and save are called only from one source it isn't needed. I would rather split implementation and declaration in separate files than inlining because as I read, i/o functions should not be inlined?!

**Comment by jiriklepl** [comment]
As I said, the keyword `inline` does not mean inlining. If you define a function in a header file outside of a class scope, it should be marked `inline` so the linker understands that multiple appearances of this function in different translation units refer to the same function.

For actual inlining, there are some pragmas and attributes - but they are not standardized

**Comment by jiriklepl** [comment]
I've looked at the new design of XYZ and I think it looks alright

**Pull request closed without merging**
